// This file is auto-generated by @hey-api/openapi-ts

export const AudioResponseSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        audio_data: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Audio Data'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'AudioResponse'
} as const;

export const Body_generate_audio_responseSchema = {
    properties: {
        text: {
            type: 'string',
            title: 'Text'
        },
        voice: {
            type: 'string',
            title: 'Voice',
            default: 'belinda'
        }
    },
    type: 'object',
    required: ['text'],
    title: 'Body_generate_audio_response'
} as const;

export const Body_transcribe_audioSchema = {
    properties: {
        audio_file: {
            type: 'string',
            format: 'binary',
            title: 'Audio File'
        }
    },
    type: 'object',
    required: ['audio_file'],
    title: 'Body_transcribe_audio'
} as const;

export const Body_upload_audioSchema = {
    properties: {
        audio_file: {
            type: 'string',
            format: 'binary',
            title: 'Audio File'
        }
    },
    type: 'object',
    required: ['audio_file'],
    title: 'Body_upload_audio'
} as const;

export const BookmarkCreateSchema = {
    properties: {
        simulation_id: {
            type: 'integer',
            title: 'Simulation Id'
        },
        message_id: {
            type: 'integer',
            title: 'Message Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['simulation_id', 'message_id', 'name'],
    title: 'BookmarkCreate'
} as const;

export const BookmarkResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        simulation_id: {
            type: 'integer',
            title: 'Simulation Id'
        },
        message_id: {
            type: 'integer',
            title: 'Message Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'simulation_id', 'message_id', 'name'],
    title: 'BookmarkResponse'
} as const;

export const CaseCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        party_a: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Party A'
        },
        party_b: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Party B'
        },
        context: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Context'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CaseCreate'
} as const;

export const CaseUpdateSchema = {
    properties: {
        party_a: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Party A'
        },
        party_b: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Party B'
        },
        key_issues: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Key Issues'
        },
        general_notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'General Notes'
        }
    },
    type: 'object',
    title: 'CaseUpdate'
} as const;

export const CaseWithTreeCountSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        party_a: {
            type: 'string',
            title: 'Party A'
        },
        party_b: {
            type: 'string',
            title: 'Party B'
        },
        context: {
            type: 'string',
            title: 'Context'
        },
        summary: {
            type: 'string',
            title: 'Summary'
        },
        last_modified: {
            type: 'string',
            format: 'date-time',
            title: 'Last Modified'
        },
        scenario_count: {
            type: 'integer',
            title: 'Scenario Count'
        }
    },
    type: 'object',
    required: ['id', 'name', 'party_a', 'party_b', 'context', 'summary', 'last_modified', 'scenario_count'],
    title: 'CaseWithTreeCount'
} as const;

export const ContextResponseSchema = {
    properties: {
        context: {
            type: 'string',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['context'],
    title: 'ContextResponse'
} as const;

export const ContinueConversationRequestSchema = {
    properties: {
        case_id: {
            type: 'integer',
            title: 'Case Id'
        },
        message_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message Id'
        },
        tree_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tree Id'
        },
        refresh: {
            type: 'boolean',
            title: 'Refresh',
            default: false
        }
    },
    type: 'object',
    required: ['case_id'],
    title: 'ContinueConversationRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        selected: {
            type: 'boolean',
            title: 'Selected',
            default: false
        },
        simulation_id: {
            type: 'integer',
            title: 'Simulation Id'
        },
        parent_id: {
            type: 'integer',
            title: 'Parent Id'
        }
    },
    type: 'object',
    required: ['simulation_id', 'parent_id'],
    title: 'Message'
} as const;

export const ModelRequestSchema = {
    properties: {
        question: {
            type: 'string',
            title: 'Question'
        }
    },
    type: 'object',
    required: ['question'],
    title: 'ModelRequest'
} as const;

export const SimulationCreateSchema = {
    properties: {
        headline: {
            type: 'string',
            title: 'Headline'
        },
        brief: {
            type: 'string',
            title: 'Brief'
        },
        case_id: {
            type: 'integer',
            title: 'Case Id'
        }
    },
    type: 'object',
    required: ['headline', 'brief', 'case_id'],
    title: 'SimulationCreate'
} as const;

export const SimulationResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        headline: {
            type: 'string',
            title: 'Headline'
        },
        brief: {
            type: 'string',
            title: 'Brief'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        case_id: {
            type: 'integer',
            title: 'Case Id'
        }
    },
    type: 'object',
    required: ['id', 'headline', 'brief', 'created_at', 'case_id'],
    title: 'SimulationResponse'
} as const;

export const SummarizedMessageRequestSchema = {
    properties: {
        simulation_id: {
            type: 'integer',
            title: 'Simulation Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        user_input: {
            type: 'string',
            title: 'User Input'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        desired_length: {
            type: 'integer',
            title: 'Desired Length',
            default: 15
        }
    },
    type: 'object',
    required: ['simulation_id', 'parent_id', 'user_input', 'role'],
    title: 'SummarizedMessageRequest'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;