/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScenarioRouteImport } from './routes/scenario'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as CaseRouteImport } from './routes/case'
import { Route as IndexRouteImport } from './routes/index'

const ScenarioRoute = ScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseRoute = CaseRouteImport.update({
  id: '/case',
  path: '/case',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case': typeof CaseRoute
  '/cases': typeof CasesRoute
  '/scenario': typeof ScenarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case': typeof CaseRoute
  '/cases': typeof CasesRoute
  '/scenario': typeof ScenarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case': typeof CaseRoute
  '/cases': typeof CasesRoute
  '/scenario': typeof ScenarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/case' | '/cases' | '/scenario'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/case' | '/cases' | '/scenario'
  id: '__root__' | '/' | '/case' | '/cases' | '/scenario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseRoute: typeof CaseRoute
  CasesRoute: typeof CasesRoute
  ScenarioRoute: typeof ScenarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scenario': {
      id: '/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof ScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case': {
      id: '/case'
      path: '/case'
      fullPath: '/case'
      preLoaderRoute: typeof CaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseRoute: CaseRoute,
  CasesRoute: CasesRoute,
  ScenarioRoute: ScenarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
